name: Build Conda Package Linux

on: [ push ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    container: ghcr.io/i4ds/mambabuild-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build conda
        run: |
          conda mambabuild -c conda-forge .
      - name: Publish to Conda Linux
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /opt/conda/conda-bld/linux-64/aotools-*.tar.bz2 --force

  install_and_test:
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda config --append channels conda-forge
          
          conda create -n testpy39 python=3.9
          conda activate testpy39
          conda install -c i4ds aotools
          python -c "import aotools"
          
          conda create -n testpy310 python=3.10
          conda activate testpy310
          conda install -c i4ds aotools
          python -c "import aotools"

